EnclosuresASP.PL/Controllers/EmployeController.cs
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class EmployeController : Controller
    {
        EmployeService employeService = new EmployeService();

        [HttpGet]
        public ActionResult Index()
        {
            return View(employeService.Get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            EmployeVM employeVM = new EmployeVM();
            PopulatePositionList(employeVM);
            return View(employeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeVM employeVM)
        {
            if (ModelState.IsValid)
            {
                PositionService positionService = new PositionService(employeService.unitOfWork);
                Employe employe = new Employe()
                {
                    FullName = employeVM.FullName,
                    EmpPosition = employeVM.PositionID == null ? null : positionService.GetByID(employeVM.PositionID)
                };
                employeService.Insert(employe);
                employeService.Save();
                return RedirectToAction("Index");
            }
            PopulatePositionList(employeVM);
            return View(employeVM);
        }

        [HttpGet]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = employeService.GetByID(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            EmployeVM employeVM = new EmployeVM()
            {
                FullName = employe.FullName,
                EmployeID = employe.EmployeID,
            };
            if (employe.EmpPosition == null)
            {
                employeVM.PositionID = null;
                PopulatePositionList(employeVM);
            }
            else
            {
                employeVM.PositionID = employe.EmpPosition.PositionID;
                PopulatePositionList(employeVM, employe.EmpPosition.PositionID);
            }
            
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeVM employeVM, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                PositionService positionService = new PositionService(employeService.unitOfWork);

                Employe employeToUpdate = employeService.GetByID(employeVM.EmployeID);
                employeToUpdate.FullName = employeVM.FullName;
                employeToUpdate.EmpPosition = employeVM.PositionID == null ? null : positionService.GetByID(employeVM.PositionID);
                
                try
                {
                    employeService.Update(employeToUpdate);
                    employeService.Save();
                    return Redirect(returnUrl);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError("", "Объект был изменён другим пользователем. Внесённые вами изменения сохранены не будут. Откройте объект заново, чтобы отобразить актуальные данные.");
                }
            }
            PopulatePositionList(employeVM, employeVM.PositionID);
            return View(employeVM);
        }

        [HttpGet]
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = employeService.GetByID(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            EnclosureService enclosureService = new EnclosureService(employeService.unitOfWork);
            EmployeVM employeVM = new EmployeVM
            {
                Enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == id).ToList(),
                EmployeID = employe.EmployeID,
                EmpPosition = employe.EmpPosition ?? null,
                PositionID = employe.EmpPosition?.PositionID,
                FullName = employe.FullName,
                Version = employe.Version
            };
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(EmployeVM employeVM, string returnUrl)
        {
            EnclosureService enclosureService = new EnclosureService(employeService.unitOfWork);
            try
            {
                List<Enclosure> enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == employeVM.EmployeID).ToList();
                for (int i = 0; i < enclosures.Count; i++)
                {
                    enclosures[i].Supervisor = null;
                }
                employeService.Delete(employeVM.EmployeID, employeVM.Version);
                employeService.Save();
                return Redirect(returnUrl);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError("", "Объект был изменён другим пользователем. Удаление не произведено. Ниже представлены актуализированные данные.");
            }
            PositionService positionService = new PositionService(employeService.unitOfWork);
            Employe employe = employeService.GetByID(employeVM.EmployeID);
            if (employe == null)
            {
                return HttpNotFound();
            }
            employeVM = new EmployeVM
            {
                Enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == employe.EmployeID).ToList(),
                EmployeID = employe.EmployeID,
                EmpPosition = employe.EmpPosition ?? null,
                PositionID = employe.EmpPosition.PositionID,
                FullName = employe.FullName,
                Version = employe.Version
            };
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                employeService.unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Privates
        private void PopulatePositionList(EmployeVM empVM, object selectedPosition = null)
        {
            PositionService positionService = new PositionService(employeService.unitOfWork);
            SelectList posSelectList = new SelectList(positionService.Get().Select(pos => new SelectListItem { Text = pos.PosName, Value = pos.PositionID.ToString() }), selectedPosition);
            empVM.Positions = (IEnumerable<SelectListItem>)(posSelectList.Items);
        }
        #endregion
    }
}

EnclosuresASP.PL/Controllers/EnclosureController.cs
using EnclosuresASP.BLL;
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;
using System;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class EnclosureController : Controller
    {
        EnclosureService enclosureService = new EnclosureService();

        // GET: Enclosure
        [HttpGet]
        public ActionResult Index()
        {
            return View(enclosureService.Get(x => x.Temporary==false));
        }

        // GET: Enclosure/Details/?
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(enclosureService.GetByID(id));
        }

        // GET: Enclosure/Create
        [HttpGet]
        public ActionResult Create()
        {
            Enclosure enclosure = new Enclosure()
            {
                Temporary = true,
                Number = "temp",
                Username = HttpContext.User.Identity.Name,
                Blocks = new List<Block>()
            };
            enclosureService.Insert(enclosure);
            enclosureService.Save();
            EnclosureVM enclosureVM = new EnclosureVM()
            {
                EnclosureID = enclosure.EnclosureID,
                Username = enclosure.Username,
                AcceptanceDate = DateTime.Now
            };
            PopulateEmployeList(enclosureVM);
            return View(enclosureVM);
        }

        // POST: Enclosure/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EnclosureVM enclosureVM)
        {
            if (ModelState.IsValid)
            {
                EmployeService employeService = new EmployeService(enclosureService.unitOfWork);
                BlockService blockService = new BlockService(enclosureService.unitOfWork);
                TypicalBlockService typicalBlockService = new TypicalBlockService(enclosureService.unitOfWork);

                Enclosure enclosure;
                enclosure = enclosureService.GetByID(enclosureVM.EnclosureID);
                enclosure.Number = enclosureVM.Number;
                enclosure.ElisNumber = enclosureVM.ElisNumber;
                enclosure.AcceptanceDate = enclosureVM.AcceptanceDate?.ToShortDateString();
                enclosure.Lvl1Password = enclosureVM.Lvl1Password;
                enclosure.Lvl2Password = enclosureVM.Lvl2Password;
                enclosure.Lvl3Password = enclosureVM.Lvl3Password;
                enclosure.Lvl4Password = enclosureVM.Lvl4Password;
                enclosure.Lvl5Password = enclosureVM.Lvl5Password;
                enclosure.Object = enclosureVM.Object;
                enclosure.Comment = enclosureVM.Comment;
                enclosure.Supervisor = enclosureVM.EmployeID == null ? null : employeService.GetByID(enclosureVM.EmployeID);


                List<Block> blocks = blockService.Get(x => x.EnclosureID == enclosure.EnclosureID).ToList();
                if (enclosure.Blocks == null) enclosure.Blocks = new List<Block>();
                if (blocks != null)
                {
                    for (int i = 0; i < enclosure.Blocks.Count(); i++)
                    {
                        int index = blocks.FindIndex(x => x.BlockGuid == enclosure.Blocks.ToList()[i].BlockGuid);
                        if (index >= 0)
                        {
                            enclosure.Blocks.ToList()[i].BlockName = blocks[index].BlockName == null ? null : typicalBlockService.GetByID(blocks[index].BlockName.TypicalBlockID);
                            enclosure.Blocks.ToList()[i].UID = blocks[index].UID;
                            enclosure.Blocks.ToList()[i].Number = blocks[index].Number;
                            enclosure.Blocks.ToList()[i].SoftwareVersion = blocks[index].SoftwareVersion;
                            enclosure.Blocks.ToList()[i].Comment = blocks[index].Comment;
                            blocks.RemoveAt(index);
                        }
                        else
                        {
                            blockService.Delete(enclosure.Blocks.ToList()[i]);
                            i--;
                        }
                    }
                    for (int i = 0; i < blocks.Count; i++)
                    {
                        Block block = new Block()
                        {
                            BlockGuid = blocks[i].BlockGuid,
                            UID = blocks[i].UID,
                            EnclosureID = blocks[i].EnclosureID,
                            Number = blocks[i].Number,
                            SoftwareVersion = blocks[i].SoftwareVersion,
                            Comment = blocks[i].Comment,
                            BlockName = blocks[i].BlockName == null ? null : typicalBlockService.GetByID(blocks[i].BlockName.TypicalBlockID)
                        };
                        enclosure.Blocks.Add(block);
                    }
                }

                FileService fileService = new FileService(enclosureService.unitOfWork);
                List<EnclosureFile> files = fileService.Get(x => x.EnclosureID == enclosure.EnclosureID).ToList();
                if (enclosure.Files == null) enclosure.Files = new List<EnclosureFile>();
                if (files?.Count > 0)
                {
                    for (int i = 0; i < files.Count; i++)
                    {
                        files[i].Temporary = false;
                        enclosure.Files.Add(files[i]);
                    }
                }

                enclosure.Temporary = false;
                enclosureService.Update(enclosure);
                enclosureService.Save();
                return RedirectToAction("Index");
            }
            if (enclosureVM.EmployeID != null)
                PopulateEmployeList(enclosureVM, enclosureVM.EmployeID);
            else
                PopulateEmployeList(enclosureVM);
            return View(enclosureVM);
        }

        [HttpGet]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enclosure enclosure = enclosureService.GetByID(id);
            if (enclosure == null)
            {
                return HttpNotFound();
            }
            EnclosureVM enclosureVM = new EnclosureVM()
            {
                EnclosureID = enclosure.EnclosureID,
                Number = enclosure.Number,
                ElisNumber = enclosure.ElisNumber,
                AcceptanceDate = DateTime.Parse(enclosure.AcceptanceDate),
                Lvl1Password = enclosure.Lvl1Password,
                Lvl2Password = enclosure.Lvl2Password,
                Lvl3Password = enclosure.Lvl3Password,
                Lvl4Password = enclosure.Lvl4Password,
                Lvl5Password = enclosure.Lvl5Password,
                Object = enclosure.Object,
                Comment = enclosure.Comment,
                FilesJSON = JsonConvert.SerializeObject(enclosure.Files.Select(x => new { name = x.Filename, extension = Path.GetExtension(x.Filename), size = x.Bytes.Length }).ToList()),
                Version = enclosure.Version
            };
            if (enclosure.Supervisor == null)
            {
                enclosureVM.EmployeID = null;
                PopulateEmployeList(enclosureVM);
            }
            else
            {
                enclosureVM.EmployeID = enclosure.Supervisor.EmployeID;
                PopulateEmployeList(enclosureVM, enclosure.Supervisor.EmployeID);
            }
            ViewBag.returnUrl = returnUrl;
            return View(enclosureVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EnclosureVM enclosureVM, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                EmployeService employeService = new EmployeService(enclosureService.unitOfWork);
                BlockService blockService = new BlockService(enclosureService.unitOfWork);
                TypicalBlockService typicalBlockService = new TypicalBlockService(enclosureService.unitOfWork);

                Enclosure enclosureToUpdate = enclosureService.GetByID(enclosureVM.EnclosureID);
                enclosureToUpdate = enclosureService.GetByID(enclosureVM.EnclosureID);
                enclosureToUpdate.Number = enclosureVM.Number;
                enclosureToUpdate.ElisNumber = enclosureVM.ElisNumber;
                enclosureToUpdate.AcceptanceDate = enclosureVM.AcceptanceDate?.ToShortDateString();
                enclosureToUpdate.Lvl1Password = enclosureVM.Lvl1Password;
                enclosureToUpdate.Lvl2Password = enclosureVM.Lvl2Password;
                enclosureToUpdate.Lvl3Password = enclosureVM.Lvl3Password;
                enclosureToUpdate.Lvl4Password = enclosureVM.Lvl4Password;
                enclosureToUpdate.Lvl5Password = enclosureVM.Lvl5Password;
                enclosureToUpdate.Object = enclosureVM.Object;
                enclosureToUpdate.Comment = enclosureVM.Comment;
                enclosureToUpdate.Supervisor = enclosureVM.EmployeID == null ? null : employeService.GetByID(enclosureVM.EmployeID);
                enclosureToUpdate.Version = enclosureVM.Version;

                List<Block> blocks = blockService.Get(x => x.EnclosureID == enclosureToUpdate.EnclosureID).ToList();
                if (enclosureToUpdate.Blocks == null) enclosureToUpdate.Blocks = new List<Block>();
                if (blocks != null)
                {
                    for (int i = 0; i < enclosureToUpdate.Blocks.Count(); i++)
                    {

EnclosuresASP.PL/Views/Employe/Create.cshtml
@model EnclosuresASP.PL.Models.EmployeVM

@{
    ViewBag.Title = "Добавление сотрудника";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Добаивть сотрудника</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("ФИО", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Должность", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(m => Model.PositionID, Model.Positions, "Выберите должность...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Создать</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "Employe")">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/Employe/Delete.cshtml
@model EnclosuresASP.PL.Models.EmployeVM

@{
    ViewBag.Title = "Удаление записи";
}

<div class="row">
    <h4>Удалить запись о сотруднике?</h4>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-horizontal">
        @Html.HiddenFor(m => m.EmployeID)
        <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />

        <div class="form-group">
            @Html.Label("ID", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DisplayFor(m => m.EmployeID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("ФИО", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DisplayFor(m => m.FullName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Должность", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DisplayFor(m => m.EmpPosition.PosName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
    @{
        if (Model.Enclosures?.Count() > 0)
        {
            <p class="bg-danger">На этого сотрудника есть ссылки в других записях. Удаление записи о сотруднике приведёт к потере информации, ссылающейся на эту запись.</p>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Шкафы, принятые сотрудником
                </div>
                <table class="table table-striped">

                    <tr>
                        <th class="text-center">Номер ШЭ</th>
                        <th class="text-center">Номер ЭЛИС</th>
                        <th class="text-center">Принял</th>
                        <th class="text-center">Дата приёмки</th>
                        <th class="text-center">Объект</th>
                        <th class="text-center">Блоки</th>
                        <th class="text-center">Файлы</th>
                        <th class="text-center">Комментарий</th>
                        <th></th>
                    </tr>

                    @if (Model.Enclosures.Count() == 0)
                    {
                        <tr>
                            <td colspan="8" class="text-center">Нет ни одной записи</td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model.Enclosures)
                        {
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Number)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.ElisNumber)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Supervisor.EmpPosition.PosName)
                                    <br />
                                    @Html.DisplayFor(modelItem => item.Supervisor.FullName)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.AcceptanceDate)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Object)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Blocks.Count)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Files.Count)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Comment)
                                </td>
                                <td class="text-center">
                                    @{
                                        string editBtnName = "editBtn" + item.EnclosureID;
                                        string deleteBtnName = "deleteBtn" + item.EnclosureID;
                                        <button id=@editBtnName name=@editBtnName class="k-primary" type="button" data-url="@Url.Action("Edit", "Enclosure", new { id = item.EnclosureID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri })">Редактировать</button>
                                        <button id=@deleteBtnName name=@deleteBtnName class="k-primary" type="button" data-url="@Url.Action("Delete", "Enclosure", new { id = item.EnclosureID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri  })">Удалить</button>

                                        <script type="text/javascript">
                                            $('.k-primary').kendoButton().click(function () {
                                                var url = $(this).data('url');
                                                window.location.href = url;
                                            });
                                        </script>
                                    }
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        }
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.EmployeID)
        @Html.HiddenFor(x => x.FullName)
        @Html.HiddenFor(x => x.PositionID)
        @Html.HiddenFor(x => x.Version)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="deleteBtn" name="deleteBtn" class="k-primary" type="submit">Удалить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@ViewBag.returnUrl">Отмена</button>
                    <script type="text/javascript">
                        $("#deleteBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    }


</div>

EnclosuresASP.PL/Views/Employe/Edit.cshtml
@model EnclosuresASP.PL.Models.EmployeVM

@{
    ViewBag.Title = "Редактирование записи о сотруднике";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование записи о сотруднике</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeID)
        @Html.HiddenFor(model => model.Version)
        <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />

        <div class="form-group">
            @Html.Label("ФИО", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Должность", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(m => Model.PositionID, Model.Positions, "Выберите должность...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Применить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@ViewBag.returnUrl">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/Employe/Index.cshtml
@model IEnumerable<EnclosuresASP.DAL.Entities.Employe>

@{
    ViewBag.Title = "Список сотрудников";
}

<br />
<p>
    <button id="addBtn" name="addBtn" class="k-primary" type="button" data-url="@Url.Action("Create", "Employe")">Добавить</button>
    <script type="text/javascript">
        $("#addBtn").kendoButton().click(function () {
            var url = $(this).data('url');
            window.location.href = url;
        });
    </script>
</p>

@*@using (Html.BeginForm())
    {
        <p>
            Select Department: @Html.DropDownList("SelectedDepartment", "All")
            <input type="submit" value="Filter" />
        </p>
    }*@

<div class="panel panel-primary">
    <div class="panel-heading">
        Список сотрудников
    </div>
    <table class="table table-striped">

        <tr>
            <th class="text-center">ID</th>
            <th class="text-center">ФИО</th>
            <th class="text-center">Должность</th>
            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">Нет ни одной записи</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.EmployeID)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.EmpPosition.PosName)
                    </td>
                    <td class="text-center">
                        @{
                            string editBtnName = "editBtn" + item.EmployeID;
                            string detailsBtnName = "detailsBtn" + item.EmployeID;
                            string deleteBtnName = "deleteBtn" + item.EmployeID;
                            <button id=@editBtnName name=@editBtnName class="k-primary" type="button" data-url="@Url.Action("Edit", "Employe", new { id = item.EmployeID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri   })">Редактировать</button>

                            <button id=@deleteBtnName name=@deleteBtnName class="k-primary" type="button" data-url="@Url.Action("Delete", "Employe", new { id = item.EmployeID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri  })">Удалить</button>

                            <script type="text/javascript">
                                $('.k-primary').kendoButton().click(function () {
                                    var url = $(this).data('url');
                                    window.location.href = url;
                                });
                            </script>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>