EnclosuresASP.PL/Controllers/BlockController.cs
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class BlockController : Controller
    {
        BlockService blockService = new BlockService();

        [HttpGet]
        public ActionResult Index()
        {
            return View(blockService.Get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            BlockVM blockVM = new BlockVM();
            PopulateBlockList(blockVM);
            return View(blockVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlockVM blockVM)
        {
            if (ModelState.IsValid)
            {
                TypicalBlockService typicalBlockService = new TypicalBlockService();
                Block block = new Block()
                {
                    UID = blockVM.UID,
                    EnclosureID = blockVM.EnclosureID,
                    BlockName = blockVM.TypicalBlockID == null ? null : typicalBlockService.GetByID(blockVM.TypicalBlockID),
                    Number = blockVM.Number,
                    SoftwareVersion = blockVM.SoftwareVersion,
                    Comment = blockVM.Comment
                };
                blockService.Insert(block);
                blockService.Save();
                return RedirectToAction("Index");
            }
            PopulateBlockList(blockVM);
            return View(blockVM);
        }

        [HttpGet]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Block block = blockService.GetByID(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            BlockVM blockVM = new BlockVM()
            {
                BlockID = block.BlockID,
                UID = block.UID,
                Number = block.Number,
                SoftwareVersion = block.SoftwareVersion,
                Comment = block.Comment
            };
            if (block.BlockName == null)
            {
                blockVM.TypicalBlockID = null;
                PopulateBlockList(blockVM);
            }
            else
            {
                blockVM.TypicalBlockID = block.BlockName.TypicalBlockID;
                PopulateBlockList(blockVM, blockVM.TypicalBlockID);
            }
            ViewBag.returnUrl = returnUrl;
            return View(blockVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BlockVM blockVM, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                TypicalBlockService typicalBlockService = new TypicalBlockService();
                Block blockToUpdate = blockService.GetByID(blockVM.BlockID);

                blockToUpdate.UID = blockVM.UID;
                blockToUpdate.BlockName = blockVM.TypicalBlockID == null ? null : typicalBlockService.GetByID(blockVM.TypicalBlockID);
                blockToUpdate.Number = blockVM.Number;
                blockToUpdate.SoftwareVersion = blockVM.SoftwareVersion;
                blockToUpdate.Comment = blockVM.Comment;

                blockService.Update(blockToUpdate);
                blockService.Save();
                return Redirect(returnUrl);
            }
            PopulateBlockList(blockVM, blockVM.TypicalBlockID);
            return View(blockVM);
        }

        [HttpGet]
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Block block = blockService.GetByID(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            BlockVM blockVM = new BlockVM()
            {
                UID = block.UID,
                BlockGuid = block.BlockGuid,
                BlockName = block.BlockName,
                Number = block.Number,
                SoftwareVersion = block.SoftwareVersion,
                Comment = block.Comment
            };
            ViewBag.returnUrl = returnUrl;
            return View(blockVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(BlockVM blockVM, string returnUrl)
        {
            try
            {
                blockService.Delete(blockVM.BlockID, blockVM.Version);
                blockService.Save();
                return Redirect(returnUrl);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError("", "Объект был изменён другим пользователем. Удаление не произведено. Ниже представлены актуализированные данные.");
            }
            Block block = blockService.GetByID(blockVM.BlockID);
            if (block == null)
            {
                return HttpNotFound();
            }
            blockVM = new BlockVM()
            {
                UID = block.UID,
                BlockGuid = block.BlockGuid,
                BlockName = block.BlockName,
                Number = block.Number,
                SoftwareVersion = block.SoftwareVersion,
                Comment = block.Comment
            };
            ViewBag.returnUrl = returnUrl;
            return View(blockVM);
        }

        #region Privates
        private void PopulateBlockList(BlockVM blockVM, object selectedBlocks = null)
        {
            TypicalBlockService typicalBlock = new TypicalBlockService();
            SelectList tBlockSelectList = new SelectList(typicalBlock.Get().Select(emp => new SelectListItem { Text = emp.BlockName, Value = emp.TypicalBlockID.ToString() }), selectedBlocks);
            blockVM.TypicalBlocks = (IEnumerable<SelectListItem>)(tBlockSelectList.Items);
        }
        #endregion
    }
}

EnclosuresASP.PL/Controllers/TypicalBlockController.cs
using System.Data.Entity.Infrastructure;
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class TypicalBlockController : Controller
    {
        TypicalBlockService typicalBlockService = new TypicalBlockService();

        [HttpGet]
        public ActionResult Index()
        {
            return View(typicalBlockService.Get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TypicalBlock typicalBlock)
        {
            if (ModelState.IsValid)
            {
                typicalBlockService.Insert(typicalBlock);
                typicalBlockService.Save();
                return RedirectToAction("Index");
            }
            return View(typicalBlock);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypicalBlock typicalBlock = typicalBlockService.GetByID(id);
            if (typicalBlock == null)
            {
                return HttpNotFound();
            }
            return View(typicalBlock);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TypicalBlock typicalBlock)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    typicalBlockService.Update(typicalBlock);
                    typicalBlockService.Save();
                    return RedirectToAction("Index");
                }
                catch(DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError("", "Объект был изменён другим пользователем. Внесённые вами изменения сохранены не будут. Откройте объект заново, чтобы отобразить актуальные данные.");
                }
            }
            return View(typicalBlock);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypicalBlock typicalBlock = typicalBlockService.GetByID(id);
            if (typicalBlock == null)
            {
                return HttpNotFound();
            }
            BlockService blockService = new BlockService(typicalBlockService.unitOfWork);
            TypicalBlockVM typicalBlockVM = new TypicalBlockVM()
            {
                Blocks = blockService.Get().Where(x => x.BlockName?.TypicalBlockID == typicalBlock.TypicalBlockID).ToList(),
                TypicalBlockID = typicalBlock.TypicalBlockID,
                BlockName = typicalBlock.BlockName,
                Version = typicalBlock.Version
            };
            return View(typicalBlockVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(TypicalBlockVM typicalBlockVM)
        {
            BlockService blockService = new BlockService(typicalBlockService.unitOfWork);
            TypicalBlock typicalBlock = new TypicalBlock()
            {
                Version = typicalBlockVM.Version,
                TypicalBlockID = typicalBlockVM.TypicalBlockID,
                BlockName = typicalBlockVM.BlockName
            };

            try
            {
                List<Block> blocks = blockService.Get().Where(x => x.BlockName?.TypicalBlockID == typicalBlock.TypicalBlockID).ToList();
                for (int i = 0; i < blocks.Count; i++)
                {
                    blocks[i].BlockName = null;
                }
                typicalBlockService.Delete(typicalBlock.TypicalBlockID, typicalBlock.Version);
                typicalBlockService.Save();
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError("", "Объект был изменён другим пользователем. Удаление невозможно. Откройте объект заново, чтобы отобразить актуальные данные.");
            }
            typicalBlockVM.Blocks = blockService.Get().Where(x => x.BlockName?.TypicalBlockID == typicalBlock.TypicalBlockID).ToList();
            return View(typicalBlockVM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                typicalBlockService.unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnclosuresASP.PL/Views/TypicalBlock/Create.cshtml
@model EnclosuresASP.DAL.Entities.TypicalBlock

@{
    ViewBag.Title = "Добавление типовой блок";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Добаивть типовой блок</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.BlockName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlockName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Создать</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "TypicalBlock")">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/TypicalBlock/Delete.cshtml
@model EnclosuresASP.PL.Models.TypicalBlockVM

@{
    ViewBag.Title = "Удаление типового блока";
}

<div class="row">
    <h4>Удалить типовой блок?</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row col-md-offset-3">
            @Html.Label("ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DisplayFor(m => m.TypicalBlockID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="row col-md-offset-3">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DisplayFor(m => m.BlockName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>

    @{
        if (Model.Blocks?.Count() > 0)
        {
            <br />
            <div class="col-md-offset-2 col-md-10">
                <p class="bg-danger">Тип присвоен блокам. Удаление записи приведёт к потере информации, ссылающейся на эту запись.</p>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Блоки
                    </div>
                    <table class="table table-striped">
                        <tr>
                            <th class="text-center">Тип</th>
                            <th class="text-center">UID</th>
                            <th class="text-center">Заводской №</th>
                            <th class="text-center">Версия ПО</th>
                            <th class="text-center">Комментарий</th>
                            <th class="text-center">Действия</th>
                        </tr>
                        @if (Model.Blocks.Count() == 0)
                        {
                            <tr>
                                <td colspan="6" class="text-center">Нет ни одного блока</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model.Blocks)
                            {
                                <tr>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.BlockName.BlockName)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.UID)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Number)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.SoftwareVersion)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Comment)
                                    </td>
                                    <td class="text-center">
                                        @{
                                            string editBtnName = "editBlockBtn" + item.BlockID;
                                            string deleteBtnName = "deleteBlockBtn" + item.BlockID;
                                            <button id=@editBtnName name=@editBtnName class="blockEditBtn k-primary" type="button" data-url="@Url.Action("Edit", "Block", new { id = item.BlockID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri })">Редактировать</button>
                                            <button id=@deleteBtnName name=@deleteBtnName class="blockDeleteBtn k-primary" type="button" data-url="@Url.Action("Delete", "Block", new { id = item.BlockID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri })">Удалить</button>
                                        }
                                        <script type="text/javascript">
                                            $('.k-primary').kendoButton().click(function () {
                                                var url = $(this).data('url');
                                                window.location.href = url;
                                            });
                                        </script>

                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        }
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.TypicalBlockID)
        @Html.HiddenFor(x => x.Version)
        @Html.HiddenFor(x => x.BlockName)

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <div class="btn-group">
                    <button id="deleteBtn" name="deleteBtn" class="k-primary" type="submit">Удалить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "TypicalBlock")">Отмена</button>
                    <script type="text/javascript">
                        $("#deleteBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    }


</div>

EnclosuresASP.PL/Views/TypicalBlock/Edit.cshtml
@model EnclosuresASP.DAL.Entities.TypicalBlock

@{
    ViewBag.Title = "Редактирование типового блока";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование типового блока</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x=>x.TypicalBlockID)
        @Html.HiddenFor(x=>x.Version)

        <div class="form-group">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.BlockName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlockName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Применить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "TypicalBlock")">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/TypicalBlock/Index.cshtml
@model IEnumerable<EnclosuresASP.DAL.Entities.TypicalBlock>

@{
    ViewBag.Title = "Список типовых блоков";
}

<br />
<p>
    <button id="addBtn" name="addBtn" class="k-primary" type="button" data-url="@Url.Action("Create", "TypicalBlock")">Добавить</button>
    <script type="text/javascript">
        $("#addBtn").kendoButton().click(function () {
            var url = $(this).data('url');
            window.location.href = url;
        });
    </script>
</p>

@*@using (Html.BeginForm())
    {
        <p>
            Select Department: @Html.DropDownList("SelectedDepartment", "All")
            <input type="submit" value="Filter" />
        </p>
    }*@

<div class="panel panel-primary">
    <div class="panel-heading">
        Список типовых блоков
    </div>
    <table class="table table-striped">

        <tr>
            <th class="text-center">ID</th>
            <th class="text-center">Наименование</th>
            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="2" class="text-center">Нет ни одной записи</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.TypicalBlockID)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.BlockName)
                    </td>
                    <td class="text-center">
                        @{
                            string editBtnName = "editBtn" + item.TypicalBlockID;
                            string detailsBtnName = "detailsBtn" + item.TypicalBlockID;
                            string deleteBtnName = "deleteBtn" + item.TypicalBlockID;
                            <button id=@editBtnName name=@editBtnName class="k-primary" type="button" data-url="@Url.Action("Edit", "TypicalBlock", new { id = item.TypicalBlockID })">Редактировать</button>

                            <button id=@deleteBtnName name=@deleteBtnName class="k-primary" type="button" data-url="@Url.Action("Delete", "TypicalBlock", new { id = item.TypicalBlockID })">Удалить</button>

                            <script type="text/javascript">
                                $('.k-primary').kendoButton().click(function () {
                                    var url = $(this).data('url');
                                    window.location.href = url;
                                });
                            </script>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>