EnclosuresASP.PL/Controllers/EmployeController.cs
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class EmployeController : Controller
    {
        EmployeService employeService = new EmployeService();

        [HttpGet]
        public ActionResult Index()
        {
            return View(employeService.Get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            EmployeVM employeVM = new EmployeVM();
            PopulatePositionList(employeVM);
            return View(employeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeVM employeVM)
        {
            if (ModelState.IsValid)
            {
                PositionService positionService = new PositionService(employeService.unitOfWork);
                Employe employe = new Employe()
                {
                    FullName = employeVM.FullName,
                    EmpPosition = employeVM.PositionID == null ? null : positionService.GetByID(employeVM.PositionID)
                };
                employeService.Insert(employe);
                employeService.Save();
                return RedirectToAction("Index");
            }
            PopulatePositionList(employeVM);
            return View(employeVM);
        }

        [HttpGet]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = employeService.GetByID(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            EmployeVM employeVM = new EmployeVM()
            {
                FullName = employe.FullName,
                EmployeID = employe.EmployeID,
            };
            if (employe.EmpPosition == null)
            {
                employeVM.PositionID = null;
                PopulatePositionList(employeVM);
            }
            else
            {
                employeVM.PositionID = employe.EmpPosition.PositionID;
                PopulatePositionList(employeVM, employe.EmpPosition.PositionID);
            }
            
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeVM employeVM, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                PositionService positionService = new PositionService(employeService.unitOfWork);

                Employe employeToUpdate = employeService.GetByID(employeVM.EmployeID);
                employeToUpdate.FullName = employeVM.FullName;
                employeToUpdate.EmpPosition = employeVM.PositionID == null ? null : positionService.GetByID(employeVM.PositionID);
                
                try
                {
                    employeService.Update(employeToUpdate);
                    employeService.Save();
                    return Redirect(returnUrl);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError("", "Объект был изменён другим пользователем. Внесённые вами изменения сохранены не будут. Откройте объект заново, чтобы отобразить актуальные данные.");
                }
            }
            PopulatePositionList(employeVM, employeVM.PositionID);
            return View(employeVM);
        }

        [HttpGet]
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employe employe = employeService.GetByID(id);
            if (employe == null)
            {
                return HttpNotFound();
            }
            EnclosureService enclosureService = new EnclosureService(employeService.unitOfWork);
            EmployeVM employeVM = new EmployeVM
            {
                Enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == id).ToList(),
                EmployeID = employe.EmployeID,
                EmpPosition = employe.EmpPosition ?? null,
                PositionID = employe.EmpPosition?.PositionID,
                FullName = employe.FullName,
                Version = employe.Version
            };
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(EmployeVM employeVM, string returnUrl)
        {
            EnclosureService enclosureService = new EnclosureService(employeService.unitOfWork);
            try
            {
                List<Enclosure> enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == employeVM.EmployeID).ToList();
                for (int i = 0; i < enclosures.Count; i++)
                {
                    enclosures[i].Supervisor = null;
                }
                employeService.Delete(employeVM.EmployeID, employeVM.Version);
                employeService.Save();
                return Redirect(returnUrl);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError("", "Объект был изменён другим пользователем. Удаление не произведено. Ниже представлены актуализированные данные.");
            }
            PositionService positionService = new PositionService(employeService.unitOfWork);
            Employe employe = employeService.GetByID(employeVM.EmployeID);
            if (employe == null)
            {
                return HttpNotFound();
            }
            employeVM = new EmployeVM
            {
                Enclosures = enclosureService.Get().Where(x => x.Supervisor?.EmployeID == employe.EmployeID).ToList(),
                EmployeID = employe.EmployeID,
                EmpPosition = employe.EmpPosition ?? null,
                PositionID = employe.EmpPosition.PositionID,
                FullName = employe.FullName,
                Version = employe.Version
            };
            ViewBag.returnUrl = returnUrl;
            return View(employeVM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                employeService.unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Privates
        private void PopulatePositionList(EmployeVM empVM, object selectedPosition = null)
        {
            PositionService positionService = new PositionService(employeService.unitOfWork);
            SelectList posSelectList = new SelectList(positionService.Get().Select(pos => new SelectListItem { Text = pos.PosName, Value = pos.PositionID.ToString() }), selectedPosition);
            empVM.Positions = (IEnumerable<SelectListItem>)(posSelectList.Items);
        }
        #endregion
    }
}

EnclosuresASP.PL/Controllers/PositionController.cs
using EnclosuresASP.BLL.Services;
using EnclosuresASP.DAL.Entities;
using EnclosuresASP.PL.ActivityTrack;
using EnclosuresASP.PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;

namespace EnclosuresASP.PL.Controllers
{
    [Authorize]
    [TraceFilter]
    public class PositionController : Controller
    {
        PositionService positionService = new PositionService();

        [HttpGet]
        public ActionResult Index()
        {
            return View(positionService.Get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Position position)
        {
            if (ModelState.IsValid)
            {
                positionService.Insert(position);
                positionService.Save();
                return RedirectToAction("Index");
            }
            return View(position);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = positionService.GetByID(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Position position)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    positionService.Update(position);
                    positionService.Save();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError("", "Объект был изменён другим пользователем. Внесённые вами изменения сохранены не будут. Откройте объект заново, чтобы отобразить актуальные данные.");
                }
            }
            return View(position);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = positionService.GetByID(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            EmployeService employeService = new EmployeService(positionService.unitOfWork);
            PositionVM positionVM = new PositionVM()
            {
                Employes = employeService.Get().Where(x => x.EmpPosition?.PositionID == position.PositionID).ToList(),
                PositionID = position.PositionID,
                PosName = position.PosName,
                Version = position.Version
            };
            return View(positionVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(PositionVM positionVM)
        {
            EmployeService employeService = new EmployeService(positionService.unitOfWork);
            Position position = new Position()
            {
                PositionID = positionVM.PositionID,
                PosName = positionVM.PosName,
                Version = positionVM.Version
            };

            try
            {
                List<Employe> employes = employeService.Get().Where(x => x.EmpPosition?.PositionID == position.PositionID).ToList();
                for (int i = 0; i < employes.Count; i++)
                {
                    employes[i].EmpPosition = null;
                }

                positionService.Delete(position.PositionID, position.Version);
                positionService.Save();
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError("", "Объект был изменён другим пользователем. Удаление невозможно. Откройте объект заново, чтобы отобразить актуальные данные.");
            }
            positionVM.Employes = employeService.Get().Where(x => x.EmpPosition?.PositionID == position.PositionID).ToList();
            return View(positionVM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                positionService.unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnclosuresASP.PL/Views/Position/Create.cshtml
@model EnclosuresASP.DAL.Entities.Position

@{
    ViewBag.Title = "Добавление должности";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Добаивть должность</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PosName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PosName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Создать</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "Position")">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/Position/Delete.cshtml
@model EnclosuresASP.PL.Models.PositionVM

@{
    ViewBag.Title = "Удаление записи";
}

<div class="row">
    <h4>Удалить должность?</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row col-md-offset-3">
            @Html.Label("ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DisplayFor(m => m.PositionID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="row col-md-offset-3">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DisplayFor(m => m.PosName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>

    @{
        if (Model.Employes?.Count() > 0)
        {
            <br />
            <div class="col-md-offset-2 col-md-10">
                <p class="bg-danger">На эту должность назначены сотрудники. Удаление записи приведёт к потере информации, ссылающейся на эту запись.</p>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Сотрудники
                    </div>
                    <table class="table table-striped">

                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">ФИО</th>
                            <th></th>
                        </tr>

                        @if (Model.Employes?.Count() == 0)
                        {
                            <tr>
                                <td colspan="6" class="text-center">Нет ни одной записи</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model.Employes)
                            {
                                <tr>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.EmployeID)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.FullName)
                                    </td>
                                    <td class="text-center">
                                        @{
                                            string editBtnName = "editBtn" + item.EmployeID;
                                            string detailsBtnName = "detailsBtn" + item.EmployeID;
                                            string deleteBtnName = "deleteBtn" + item.EmployeID;
                                            <button id=@editBtnName name=@editBtnName class="k-primary" type="button" data-url="@Url.Action("Edit", "Employe", new { id = item.EmployeID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri  })">Редактировать</button>

                                            <button id=@deleteBtnName name=@deleteBtnName class="k-primary" type="button" data-url="@Url.Action("Delete", "Employe", new { id = item.EmployeID, returnUrl = HttpContext.Current.Request.Url.AbsoluteUri  })">Удалить</button>

                                            <script type="text/javascript">
                                                $('.k-primary').kendoButton().click(function () {
                                                    var url = $(this).data('url');
                                                    window.location.href = url;
                                                });
                                            </script>
                                        }
                                    </td>
                                </tr>
                                                }
                                            }
                    </table>
                </div>
            </div>
                                            }
    }

    @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.PositionID)
        @Html.HiddenFor(x => x.Version)
        @Html.HiddenFor(x => x.PosName)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="deleteBtn" name="deleteBtn" class="k-primary" type="submit">Удалить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "Position")">Отмена</button>
                    <script type="text/javascript">
                        $("#deleteBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    }


</div>

EnclosuresASP.PL/Views/Position/Edit.cshtml
@model EnclosuresASP.DAL.Entities.Position

@{
    ViewBag.Title = "Редактирование должности";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование должности</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x=> x.PositionID)
        @Html.HiddenFor(x => x.Version)

        <div class="form-group">
            @Html.Label("Наименование", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PosName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PosName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group">
                    <button id="submitBtn" name="submitBtn" class="k-primary" type="submit">Применить</button>
                    <button id="cancelBtn" name="cancelBtn" class="k-default" type="button" data-url="@Url.Action("Index", "Position")">Отмена</button>
                    <script type="text/javascript">
                        $("#submitBtn").kendoButton();
                        $("#cancelBtn").kendoButton().click(function () {
                            var url = $(this).data('url');
                            window.location.href = url;
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnclosuresASP.PL/Views/Position/Index.cshtml
@model IEnumerable<EnclosuresASP.DAL.Entities.Position>

@{
    ViewBag.Title = "Список должностей";
}

<br />
<p>
    <button id="addBtn" name="addBtn" class="k-primary" type="button" data-url="@Url.Action("Create", "Position")">Добавить</button>
    <script type="text/javascript">
        $("#addBtn").kendoButton().click(function () {
            var url = $(this).data('url');
            window.location.href = url;
        });
    </script>
</p>

@*@using (Html.BeginForm())
    {
        <p>
            Select Department: @Html.DropDownList("SelectedDepartment", "All")
            <input type="submit" value="Filter" />
        </p>
    }*@

<div class="panel panel-primary">
    <div class="panel-heading">
        Список должностей
    </div>
    <table class="table table-striped">

        <tr>
            <th class="text-center">ID</th>
            <th class="text-center">Наименование</th>
            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="2" class="text-center">Нет ни одной записи</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.PositionID)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.PosName)
                    </td>
                    <td class="text-center">
                        @{
                            string editBtnName = "editBtn" + item.PositionID;
                            string detailsBtnName = "detailsBtn" + item.PositionID;
                            string deleteBtnName = "deleteBtn" + item.PositionID;
                            <button id=@editBtnName name=@editBtnName class="k-primary" type="button" data-url="@Url.Action("Edit", "Position", new { id = item.PositionID })">Редактировать</button>

                            <button id=@deleteBtnName name=@deleteBtnName class="k-primary" type="button" data-url="@Url.Action("Delete", "Position", new { id = item.PositionID })">Удалить</button>

                            <script type="text/javascript">
                                $('.k-primary').kendoButton().click(function () {
                                    var url = $(this).data('url');
                                    window.location.href = url;
                                });
                            </script>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>